language: python

python:
  - "3.6"
  - "3.7"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - "pip install pipenv --upgrade"
  - "pipenv install --dev --skip-lock"

script:
  - "pipenv run pytest -n 8 --boxed"

jobs:
  include:
    - stage: codestyle
      python: 3.6
      script:
        - "pipenv run flake8"
    - stage: coverage
      python: 3.6
      script:
        - "pipenv run pytest --cov=maru"
        - "pipenv run codecov"
