language: python

python:
  - "3.5"
  - "3.6"

install:
  - "pip install pipenv --upgrade"
  - "pipenv install --dev --skip-lock"

script:
  - "pipenv run pytest -n 8 --boxed"

jobs:
  include:
    - stage: codestyle
      python: 3.5
      script:
        - "pipenv run flake8"
    - stage: coverage
      python: 3.5
      script:
        - "pipenv run pytest --cov=maru"
        - "pipenv run codecov"
