language: python

python:
  - 3.6

install:
  - "pip install pipenv --upgrade"
  - "pipenv install --dev"

jobs:
  include:
    - stage: test
      python: 3.6
      script:
        - "pipenv run pytest -n 8 --boxed"
    - stage: codestyle
      python: 3.6
      script:
        - "pipenv run flake8"
    - stage: coverage
      python: 3.6
      script:
        - "pipenv run pytest --cov=maru"
        - "pipenv run codecov"
